version: "3"

services:
    backend: &api
        build: ./api
        image: api_aflore
        volumes:
            - .:/code
        ports:
            - "8000:8000"

    #frontend: &ui
    #    container_name: ui
    #    build: ./ui
    #    volumes:
    #        - '.:/code'
    #        - '/code/node_modules'
    #    ports:
    #        - 3000:3000
    #    stdin_open: true
    #    environment:
    #       - CHOKIDAR_USEPOLLING=true
    #    command: npm start 

    react:
            build: ./ui
            image: cowork_ui
            ports:
                - "80:80"
